spring:
  datasource:
    url: 'jdbc:h2:mem:test'
    username: 'user'
    password: ''
    driver-class-name: org.h2.Driver

    thymeleaf:
      prefix: classpath:/static/

h2.console:
  enabled: true # ?? ?? ??, ???? ? ?????? ?? ??

jpa:
  hibernate:
    ddl-auto: create # ???? ???? ???
  properties:
    hibernate:
      format_sql: true # SQL ?? ??

logging:
level:
  org.hibernate.SQL: debug # SQL ?? ??? ?? ?? ?? ??


